version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run:
          command: npm install && npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
